### ISSUE TITLE
❤️ Hello, I like this effect very much.

### ISSUE THREAD

**Issue by XboxYan** [AlexMubarakshin/mu-vis#1]
❤️ Hello, I like this effect very much.

I've done similar things before.Here's a demo.

[https://web.codelabo.cn/demo/20181121-music.html](https://web.codelabo.cn/demo/20181121-music.html)

[https://web.codelabo.cn/demo/20181121-music-circle.html](https://web.codelabo.cn/demo/20181121-music-circle.html)

**Comment by AlexMubarakshin** [comment]
@XboxYan Cool! If you want to improve project, welcome to contribute! 😊
